trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CacheBeta@1
  inputs:
    key: 'stackcache'
    path: '.stack-work'
- script: |
    sudo apt-get update
    sudo apt-get install libgirepository1.0-dev libwebkit2gtk-4.0-dev libgtksourceview-3.0-dev
    sudo apt-get install libsdl2-dev
    stack test
  displayName: 'Run tests'
