resolver: lts-15.8

packages:
- .

compiler: ghc-8.10.1

extra-deps: 
- gi-gtk-declarative-0.6.3
- gi-gtk-declarative-app-simple-0.6.3
- lens-4.19.1

require-stack-version: ">=2.1"

# compiler-check: newer-minor
